name                    HumanStateVisualizer

# Model Configuration options
modelURDFName      "humanSubject01_66dof.urdf"
ignoreMissingLinks  true
visualizeWrenches   false

# Camera options
cameraDeltaPosition  (2.0, 0.0, 0.5)
useFixedCamera       false           # if set to false, the camera follows the model base link
fixedCameraTarget    (0.0, 0.0, 0.0) # this option is unused when useFixedCamera is false
maxVisualizationFPS  65

# Client Configuration
humanStateDataPortName "/HDE/HumanStateServer/state:o"

# Human State Horizon Configuration
# Set useStateHorizon to true to read the human state from a single index of the
# IHumanStateHorizon instead of the classical IHumanState.
useStateHorizon                false
horizonIndex                   0
humanStateHorizonDataPortName  "/HDE/HumanStateHorizonServer/state:o"
